# Generated by Django 6.0.4 on 2026-04-28 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notavy', '0002_alter_user_options_user_mode_user_theme_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(default='DRK', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(default='EMB', max_length=3),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_from', 'user_to')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='notavy.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
