# Generated by Django 6.0.4 on 2026-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notavy', '0003_alter_user_mode_alter_user_theme_follow_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
