# Generated by Django 6.0.4 on 2026-04-30 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notavy', '0004_user_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
